# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
env:
   - PYTHON=""
script:
  # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # - julia -e 'Pkg.clone(pwd())'
  # - julia -e 'Pkg.test("PackageExample")'
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; pkg"add Coverage"; using Coverage; Codecov.submit(Codecov.process_folder())'
